### ISSUE TITLE
After successful Twitter authentication I am redirected to Google News

### ISSUE THREAD

**Issue by johnymontana** [neo4j-examples/graphgist_portal#32]
I follow the link from http://graphgist.neo4j.com/#!/gists (Submit GraphGist). After going through Twitter authentication from http://graphgist-portal.herokuapp.com/submit_graphgist I am redirected to http://news.google.com. I expected to be redirected back to the GraphGist Portal page.

I suspect the real issue here is that  http://graphgist.neo4j.com/#!/gists points to http://graphgist-portal.herokuapp.com/submit_graphgist and not portal.graphgist.org

**Comment by cheerfulstoic** [comment]
Weird!  Thanks for the report.  I'm not able to reproduce this, but I've updated the link from http://graphgist.neo4j.com/#!/gists because it's nice to save the redirect even if it doesn't help this issue.

Please try again, though I wonder if the issue might be around signing up rather than signing in (even though the user experience for both of those is pretty much the same with Twitter/GitHub auth)

**Comment by johnymontana** [comment]
I tried again (with a new Twitter account) and it worked fine. Closing.
