### ISSUE TITLE
HIGH priority: Redirect from neo4j.com/graphgist/(OLD ID FORMAT)

### ISSUE THREAD

**Issue by ryguyrg** [neo4j-examples/graphgist_portal#87]
HIGH priority: Redirect from neo4j.com/graphgist/(OLD ID FORMAT) to  neo4j.com/graphgist/(NEW ID FORMAT) when the Gist exists in the database.

Many popular Gists are still referencing the old URL format and it's showing the 'not approved' message.

**Comment by cheerfulstoic** [comment]
Can you give an example to test with?

**Comment by cheerfulstoic** [comment]
Nevermind, I can just get a gist ID out of the DB

**Comment by cheerfulstoic** [comment]
Have a look.  It should be fixed now.

The commit in question: https://github.com/neo4j-examples/graphgist_portal/commit/5f071ead0cb8d120d6850030e770a9e13d40e161

Basically when it figures out the raw URL for the graphgist ID it looks that up in the database and uses that GraphGist object instead of creating a new one in-memory.  It looks like there aren't any PHP changes needed because it just checks to see if it's a candidate.
